import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import LoggedNavBar from "@/components/logged-navbar";

export const metadata: Metadata = {
  title: "RSVP - Niver da Lalá!",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
        <body
        >
          <LoggedNavBar/>
          {children}
        </body>
      </html>
  );
}
